### ISSUE TITLE
布局 - TeXt Theme

### ISSUE THREAD

**Issue by kitian616** [kitian616/gitalk-demo#57]
https://tianqi.name/jekyll-TeXt-theme/docs/zh/layouts 

 A customizable Jekyll theme for your blog or site

**Comment by StruggleYang** [comment]
为何
```
---
layout: page
title: dapeng-soa
mode: immersive
header:
  theme: dark
  background: '#123'
article_header:
  type: overlay
  theme: dark
  background_color: '#123'
  background_image: false
---
```
上面的配置background_color不生效
